server:
  port: 3012
spring:
  datasource:
    username: root
    password: c6Q8aKelMS5yqTei/9KJa2WYyv4pQZ+a79gbYVmgkHva1QgfybboB7INWeG21kPq0eHDdU2B8ce1RMdSvhuSeA==
    #3fe14f9e59c2f695
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.254.155:3306/igclub?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: root
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 192.168.254.155
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password: ig1234
    # 连接超时时间
    timeout: 5s
    lettuce:
      pool:
        # 连接池最大连接数
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1ms
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0
publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIb04SqefAbD8BfI85E2mkraSzvsBlFyngU5Bf/5ibOAPQ3MOA6u6Y6crNfo5yw5SXMgkiSevAubPaNCSw/5MikCAwEAAQ==
logging:
  config: classpath:log4j2-spring.xml