server:
  port: 3010
spring:
  datasource:
    username: root
    password: c6Q8aKelMS5yqTei/9KJa2WYyv4pQZ+a79gbYVmgkHva1QgfybboB7INWeG21kPq0eHDdU2B8ce1RMdSvhuSeA==
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.43.165.160:3306/igclub?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: root
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true


publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAIb04SqefAbD8BfI85E2mkraSzvsBlFyngU5Bf/5ibOAPQ3MOA6u6Y6crNfo5yw5SXMgkiSevAubPaNCSw/5MikCAwEAAQ==
logging:
  config: classpath:log4j2-spring.xml
