server:
  port: 3000
spring:
  datasource:
    username: root
    password: QrI/mFXgSmb6XReY5DKUmftzhDlyvy8x4/TbvpCi74DwNF1sofunqMUvz03hJQgGjV6AEM4LKg5rcesEZwFULg==
    #3fe14f9e59c2f695
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost/igclub?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 20
      min-idle: 20
      max-active: 100
      max-wait: 60000
      connectionProperties: config.decrypt=true;config.decrypt.key=${publicKey};
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        login-username: root
        login-password: root
      filter:
        stat:
          enabled: true
          slow-sql-millis: 2000
          log-slow-sql: true
        wall:
          enabled: true
        config:
          enabled: true


publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAKTenYBG5Eti6ch4V5VLZ0h0gfUHqmPUv57Fc/IyE0CvCS8lPTgF7+ExHr2kgj8VKO/OS2GMRvhlnHGYNywgfqcCAwEAAQ==
logging:
  config: classpath:log4j2-spring.xml
#mybatis-plus:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl